export const SIGN_UP: string = 'SIGN_UP'
export const SIGN_IN: string = 'SIGN_IN'
export const LOGOUT: string = 'LOGOUT'
export const FORGOT_PASSWORD: string = 'FORGOT_PASSWORD'
export const SET_CHECKOUT: string = 'SET_CHECKOUT'
