export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Recover } from './RecoverPassword'
export { default as MinimalBag } from './MinimalBag'
export { default as Change } from './Change'