export const homeId = 'cG9zdDoxNg=='
export const aboutId = 'cG9zdDoxOA=='
export const generalId = 'cG9zdDo4Nw=='
export const registerId = 'cG9zdDoyMDI='
export const loginId = 'cG9zdDoyMzc='
export const authId = 'd3e29e67-f56d-4635-a285-de7cd6e4a32e'