export { default as FirstBanner } from './FirstBanner'
export { default as Contact } from './Contact'
export { default as Shop } from './Shop'
export { default as Sponsors } from './Sponsors'
export { default as Brand } from './Brand'